### ISSUE TITLE
Make this repo work with lein uberjar out of the box.

### ISSUE THREAD

**Issue by dchelimsky** [arachne-framework/enterprise-spa#4]
I'd like to be able to:

```
git clone git@github.com:arachne-framework/enterprise-spa.git
cd enterprise-spa
lein uberjar
java -cp target/enterprise-spa-0.1.0-SNAPSHOT-standalone.jar clojure.main -m arachne.run :org.arachne-framework.template/enterprise-spa :org.arachne-framework.template.enterprise-spa/runtime
```

As it stands `lein uberjar` produces the following:

```
Warning: specified :main without including it in :aot.
Implicit AOT of :main will be removed in Leiningen 3.0.0.
If you only need AOT for your uberjar, consider adding :aot :all into your
:uberjar profile instead.
Warning: The Main-Class specified does not exist within the jar. It may not be executable as expected. A gen-class directive may be missing in the namespace which contains the main method, or the namespace has not been AOT-compiled.
Created /Users/david/Dropbox/src/enterprise-spa/target/enterprise-spa-0.1.0-SNAPSHOT.jar
Created /Users/david/Dropbox/src/enterprise-spa/target/enterprise-spa-0.1.0-SNAPSHOT-standalone.jar
```

And then the `java` command above produces this:

```
21:28:44.308 INFO  - arachne.run {:msg "Launching Arachne application", :name ":org.arachne-framework.template/enterprise-spa", :runtime ":org.arachne-framework.template.enterprise-spa/runtime", :line nil}
Exception in thread "main" arachne.ArachneException: Modules `#{:org.arachne-framework/pedestal-assets :org.arachne-framework/arachne-figwheel :org.arachne-framework/arachne-sass}` not found (type = :arachne.core.module/missing-module)
	at arachne.error$arachne_ex.invokeStatic(error.clj:148)
	at arachne.error$arachne_ex.invoke(error.clj:139)
	at arachne.core.module$validate_dependencies.invokeStatic(module.clj:66)
	at arachne.core.module$validate_dependencies.invoke(module.clj:51)
	at arachne.core.module$topological_sort.invokeStatic(module.clj:86)
	at arachne.core.module$topological_sort.invoke(module.clj:81)
	at arachne.core.module$config_STAR_.invokeStatic(module.clj:199)
	at arachne.core.module$config_STAR_.invoke(module.clj:195)
	at arachne.core.module$config.invokeStatic(module.clj:241)
	at arachne.core.module$config.invoke(module.clj:228)
	at arachne.core$config.invokeStatic(core.clj:138)
	at arachne.core$config.doInvoke(core.clj:135)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at arachne.run$_main.invokeStatic(run.clj:28)
	at arachne.run$_main.doInvoke(run.clj:8)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:316)
	at clojure.main$main_opt.invoke(main.clj:312)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
```

**Comment by dchelimsky** [comment]
Thanks @levand for getting this done. Just an FYI: there is still an issue with the figwheel build when running the jar, however I don't have figwheel running in my app when I run it from the jar, so this is not an actual problem. Would you be interested in a PR with support for changing the run env (so the `dev?` fn in the config file can return false) and some doc about running it that way?

```
No such namespace: cljsjs.react, could not locate cljsjs/react.cljs, cljsjs/react.cljc, or Closure namespace "cljsjs.react"
```
